<!doctype html>
<html lang="es">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="">
    <meta name="author" content="ByBraiiaN">
    <link rel="icon" href="../favicon.ico">

    <title>CRUD - PHP MySQLi JQUERY</title>
    
    <!-- Bootstrap core CSS -->
    <link rel="stylesheet" href="assets/css/bootstrap.min.css">

    <!-- Custom styles for this template -->
    <link rel="stylesheet" href="assets/css/offcanvas.css">
    <link rel="stylesheet" href="assets/fonts/css/fontawesome-all.min.css">
  </head>